aws:
  access_key_id: DEIN_ACCESS_KEY
  secret_access_key: DEIN_SECRET_KEY
  region_name: eu-central-1
  bucket_name: DEIN_BUCKET_NAME
camera:
  resolution:
    x: 1280
    y: 854
  interval: 5 # Intervall in Sekunden, sollte 3 Sek nicht unterschreiten
  prefix: vogelcam
  output_dir: tmp_output